version: '3.6'
# https://docs.docker.com/compose/compose-file/

services:
  db:
    image: postgres:14-alpine
    volumes:
      - db_lbp:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    ports:
      - '25434:5432'

volumes:
  db_lbp:
